### PR TITLE
Redesign the UI

### PR DESCRIPTION
**Pull request by pepas24**
This pull request update the UI of the site as commented on #3

### CODE REVIEW

**Comment by jrtechs** [comment]
@pepas24 I am so ecstatic that you worked on this project. It looks great!
wowie

wowie2

The only thing I would suggest is that you update the organization view so that it has the same outlign/black box on the graph that the indivudial user has.

wowie3

You can work on that in this PR or, we can merge this one and you can do it in a separate PR, I will leave that up to you.

**Comment by pepas24** [comment]
Yes, I started the PR as draft because I haven't ended yet. But I think it is better to update all the ui in the same PR, because some styles don't aply well after my intervention. I'll updete the PR in a few days.

**Comment by pepas24** [comment]
@jrtechs I just finished the changes, please take a look and tell me what do you think.

**Comment by jrtechs** [comment]
@pepas24 I will look at this tonight.

**Comment by jrtechs** [comment]
@pepas24 I just looked at this and it looks absolutely amazing!!! I'm going to merge this now and upload it to the active server later tonight.

**Pull request merged**
