### PR TITLE
Set up repo in preparation for front end rework

### PR DESCRIPTION
**Pull request by petermorgandev**
The only file change is `.gitignore` to look in folders. The other changes are moving the server files from the root directory into a "server" folder. This will help prep the repo for the front end rework - which will be in a "client" folder.

### CODE REVIEW

**Comment by jrtechs** [comment]
@PeterMorganGH Is the idea for the front-end conversion that we create a separate folder at the root directory called "client" with its own server with a separate node js project?

**Comment by petermorgandev** [comment]
In short: Yes.

```
- Root
-- Client
-- Server
```

**Review by jrtechs — APPROVED** [review]
Cool, I like it, this will make the repository cleaner. @ct-martin make sure that you pull these changes into the front-end work.

**Comment by petermorgandev** [comment]
@jrtechs I opened a PR in @ct-martin's branch to sync the changes. Once that is merged I will try to get some more work done on the front end rework.

**Pull request merged**
